version: '3'

services:
  app:
    build:
      context: '.'
      dockerfile: 'Dockerfile.dev'
    container_name: 'ytradio-app'
    ports:
      - '3000:3000'
      - '3001:3001'
      - '3003:3003'
    volumes:
      - '.:/app'
    command: 'sh /app/entrypoint.sh'
    environment:
      - YTAPI_KEY=${YTAPI_KEY}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=ytradio
      - DB_USER=root
      - DB_PASSWORD=admin
    links: 
      - mysql
    depends_on: 
      - mysql
  mysql:
    image: 'mysql'
    container_name: 'ytradio-db'
    expose: 
      - 3306
    ports: 
      - "6033:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - ./data:/var/lib/mysql
      - ./scripts/sql:/docker-entrypoint-initdb.d
